### PR TITLE
Adds Mason Packard

### PR DESCRIPTION
**Pull request by masonpackard**

### CODE REVIEW

**Comment by RowdyChildren** [comment]
The current site is going away in a few days and we are moving to laddr

**Comment by masonpackard** [comment]
Thanks for the information.  Would I need to add my background to laddr, like is referenced here http://www.codeforcharlotte.org/add-yourself-to-website.html?

**Comment by RowdyChildren** [comment]
Not at the moment, we are currently in between sites. When the new site is up we will put it out via email and slack.

**Comment by RowdyChildren** [comment]
you can now sign up for laddr by going to codeforcharlotte.org

**Pull request closed without merging**
